name: samples_dart

permissions: read-all

on:
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/samples.yml'
      - 'pkgs/google_generative_ai/**'
      - 'samples/dart/**'
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/samples.yml'
      - 'pkgs/google_generative_ai/**'
      - 'samples/dart/**'
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: samples/dart
    strategy:
      fail-fast: false
      matrix:
        sdk: [stable, dev]
        include:
          - sdk: stable
            check-formatting: true
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
      - uses: dart-lang/setup-dart@f0ead981b4d9a35b37f30d36160575d60931ec30
        with:
          sdk: ${{ matrix.sdk }}

      - run: dart pub get

      - run: dart analyze --fatal-infos

      - run: dart format --output=none --set-exit-if-changed .
        if: ${{matrix.check-formatting}}
